server:
  port: 80

spring:
  application:
    name: consul-consumer-a
  ####consul注册中心地址
  cloud:
    consul:
      host: localhost
      port: 8500a
      discovery:
        #hostname: 127.0.0.1
        service-name: ${spring.application.name}
